_base_: base.yaml
run_name: abl5
init_from: D:/BaoYen_work/checkpoints/stage2_pmcvqa_full/best.pt
data:
  dataset: fracatlas
  max_samples: 6000
  val_max_samples: 300
  answer_vocab_size: 300
  loader_kwargs:
    with_masks: false
    with_boxes: true
model:
  use_region_in_prompt: false
train:
  stage: 3
  epochs: 2
  batch_size: 4
  grad_accum: 4
  lr: 1.0e-4
  eval_max_samples: 300
